<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'code'              => '01-CUS-00001',
                'name'              => 'សុខ ដារ៉ា',
                'gender'            => 'Male',
                'phone'             => '012345678',
                'email'             => 'sokdara@example.com',
                'address'           => 'ភ្នំពេញ',
                'national_id'       => 'KH-001-123456',
                'date_of_birth'     => '1990-03-15',
                'age_verified'      => 1,
                'occupation'        => 'អ្នកជំនួញ',
                'monthly_income'    => 1200.00,
                'has_existing_loan' => 0,
                'credit_score'      => 720,
                'type'              => 'individual',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00002',
                'name'              => 'ចាន់ ស្រីពៅ',
                'gender'            => 'Female',
                'phone'             => '098765432',
                'email'             => 'chan.sreypov@example.com',
                'address'           => 'កណ្ដាល',
                'national_id'       => 'KH-002-234567',
                'date_of_birth'     => '1985-07-22',
                'age_verified'      => 1,
                'occupation'        => 'គ្រូបង្រៀន',
                'monthly_income'    => 900.00,
                'has_existing_loan' => 1,
                'credit_score'      => 680,
                'type'              => 'individual',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00003',
                'name'              => 'លី មករា',
                'gender'            => 'Male',
                'phone'             => '011111111',
                'email'             => null,
                'address'           => 'សៀមរាប',
                'national_id'       => 'KH-003-345678',
                'date_of_birth'     => '1978-01-10',
                'age_verified'      => 1,
                'occupation'        => 'កសិករ',
                'monthly_income'    => 500.00,
                'has_existing_loan' => 0,
                'credit_score'      => 530,
                'type'              => 'individual',
                'status'            => 0,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00004',
                'name'              => 'នី ស្រីល័ក្ខ',
                'gender'            => 'Female',
                'phone'             => '022222222',
                'email'             => 'ny.sreylak@example.com',
                'address'           => 'បាត់ដំបង',
                'national_id'       => 'KH-004-456789',
                'date_of_birth'     => '1992-11-05',
                'age_verified'      => 1,
                'occupation'        => 'គណនេយ្យករ',
                'monthly_income'    => 1500.00,
                'has_existing_loan' => 0,
                'credit_score'      => 780,
                'type'              => 'business',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00005',
                'name'              => 'ហេង វុទ្ធី',
                'gender'            => 'Male',
                'phone'             => '033333333',
                'email'             => 'heng.vuthy@example.com',
                'address'           => 'តាកែវ',
                'national_id'       => 'KH-005-567890',
                'date_of_birth'     => '1988-06-30',
                'age_verified'      => 1,
                'occupation'        => 'វិស្វករ',
                'monthly_income'    => 2000.00,
                'has_existing_loan' => 1,
                'credit_score'      => 810,
                'type'              => 'individual',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00006',
                'name'              => 'ស្រី នាង',
                'gender'            => 'Female',
                'phone'             => '044444444',
                'email'             => null,
                'address'           => 'កំពង់ចាម',
                'national_id'       => 'KH-006-678901',
                'date_of_birth'     => '1975-09-18',
                'age_verified'      => 1,
                'occupation'        => 'អ្នកលក់',
                'monthly_income'    => 700.00,
                'has_existing_loan' => 1,
                'credit_score'      => 490,
                'type'              => 'individual',
                'status'            => 0,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00007',
                'name'              => 'ជា វិសាល',
                'gender'            => 'Male',
                'phone'             => '055555555',
                'email'             => 'chea.visal@example.com',
                'address'           => 'ព្រៃវែង',
                'national_id'       => 'KH-007-789012',
                'date_of_birth'     => '1995-04-25',
                'age_verified'      => 1,
                'occupation'        => 'បើកបរ',
                'monthly_income'    => 600.00,
                'has_existing_loan' => 0,
                'credit_score'      => 560,
                'type'              => 'individual',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00008',
                'name'              => 'ម៉ៅ ស្រីនិត',
                'gender'            => 'Female',
                'phone'             => '066666666',
                'email'             => 'mao.sreynit@example.com',
                'address'           => 'កំពង់ស្ពឺ',
                'national_id'       => 'KH-008-890123',
                'date_of_birth'     => '1983-12-12',
                'age_verified'      => 1,
                'occupation'        => 'ចៅហ្វាយក្រុមហ៊ុន',
                'monthly_income'    => 3500.00,
                'has_existing_loan' => 0,
                'credit_score'      => 850,
                'type'              => 'business',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00009',
                'name'              => 'ប៉ុន សុខា',
                'gender'            => 'Male',
                'phone'             => '077777777',
                'email'             => null,
                'address'           => 'កោះកុង',
                'national_id'       => 'KH-009-901234',
                'date_of_birth'     => '1970-08-08',
                'age_verified'      => 1,
                'occupation'        => 'ជាងឈើ',
                'monthly_income'    => 450.00,
                'has_existing_loan' => 1,
                'credit_score'      => 420,
                'type'              => 'individual',
                'status'            => 0,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'code'              => '01-CUS-00010',
                'name'              => 'ឡេង ស្រីមុំ',
                'gender'            => 'Female',
                'phone'             => '088888888',
                'email'             => 'leng.sreymom@example.com',
                'address'           => 'កំពត',
                'national_id'       => 'KH-010-012345',
                'date_of_birth'     => '1991-02-14',
                'age_verified'      => 1,
                'occupation'        => 'គ្រូពេទ្យ',
                'monthly_income'    => 2800.00,
                'has_existing_loan' => 0,
                'credit_score'      => 830,
                'type'              => 'business',
                'status'            => 1,
                'document_path'     => null,
                'created_by'        => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
